### ISSUE TITLE
Chokes on titles with apostrophes

### ISSUE THREAD

**Issue by mccalluc** [WGBH/cmless#14]
Invalid predicate: //h2[text()='ERN's Coverage']

**Comment by mccalluc** [comment]
We got here because openvault calls extract_html directly. In normal usage, the text of the h2 to look for comes from an attribute name on your CMLess subclass, and so there's no reason for it to be consuming apostrophes... and, if I were to do OV over again, I would split each tab into a separate md, and manage the related tabs a CMLess hierarchy.

TLDR: I don't think we should tweak the code to handle this particular case. @afred: Sound reasonable?

**Comment by afred** [comment]
sounds reasonable.

Also 👍 for the idea of changing "tabs" to simply "nested content". No urgency of course, but that makes more sense to me.
